### ISSUE TITLE
Use Intent to pick image from gallery to upload image 

### ISSUE THREAD

**Issue by Subhadiptech** [PCON-Hacktoberfest-2022/BackgroundRemoverSDK#3]

**Comment by neil0504** [comment]
hello @Subhadiptech, I would like to work on this issue. plz assign it to me.

**Comment by Subhadiptech** [comment]
Hey @neil0504 , 
Carry on

**Comment by neil0504** [comment]
Hey@Subhadiptech , i have added the pr, will u plz check it out n let me know if any changes r required
